image: 'python:3.7'

before_script:
  - python --version
  - python3 --version

stages:
  - static analysis
  - tests

flake8:
  stage: static analysis
  script:
    - nox -s flake8
  only:
    - web
    - trigger
    - merge requests
  tags:
    - pp-new-develop


isort:
  stage: static analysis
  script:
    - nox -s isort -- check
  only:
    - web
    - trigger
    - merge requests
  tags:
    - pp-new-develop


yapf:
  stage: static analysis
  script:
    - nox -s yapf -- check
  only:
    - web
    - trigger
    - merge requests
  tags:
    - pp-new-develop


mainnet:
  stage: tests
  script:
    - nox -s mainnet-tests
  only:
    - web
    - trigger
    - merge requests
  tags:
    - pp-new-develop


testnet:
  stage: tests
  script:
    - nox -s testnet-tests
  only:
    - web
    - trigger
    - merge requests
  tags:
    - pp-new-develop
