image: 'python:3.7'

stages:
  - static analysis
  - tests

.analyzers:
  stage: static analysis
  before_script:
    - pip3 install -r requirements_dev.txt --no-cache-dir
  only:
    - web
    - trigger
    - merge requests
  tags:
    - pp-new-develop

.tests:
  stage: tests
  variables:
    PYTHON_VERSION: 3
  only:
    - web
    - trigger
    - merge requests
  tags:
    - pp-new-develop

flake8:
  extends: .analyzers
  script:
    - nox -s flake8

isort:
  extends: .analyzers
  script:
    - nox -s isort -- check

yapf:
  extends: .analyzers
  script:
    - nox -s yapf -- check

mainnet:
  extends: .tests
  script:
    - nox -s mainnet-tests

testnet:
  extends: .tests
  script:
    - nox -s testnet-tests
