image: 'python:3.7'

stages:
  - static analysis
  - tests

.analyzers:
  stage: static analysis
  before_script:
    - pip3 install nox
  variables:
    PYTHON_VERSION: 3
  only:
    - web
    - trigger
    - merge_requests
  tags:
    - docker

.tests:
  stage: tests
  before_script:
    - pip3 install nox
  variables:
    PYTHON_VERSION: 3
  artifacts:
    paths:
      - reports
    expire_in: 3 hours
    when: always
  only:
    - web
    - trigger
    - merge_requests
  tags:
    - docker

flake8:
  extends: .analyzers
  script:
    - nox -s flake8

isort:
  extends: .analyzers
  script:
    - nox -s isort -- check

yapf:
  extends: .analyzers
  script:
    - nox -s yapf -- check

mypy:
  extends: .analyzers
  script:
    - nox -s mypy

mainnet:
  extends: .tests
  script:
    - nox -s mainnet-tests
  
testnet:
  extends: .tests
  script:
    - nox -s testnet-tests
