image: 'python:3.7'

before_script:
  - pip3 install -r requirements_dev.txt

stages:
  - static analysis
  - tests

static-analysis-service:
  stage: static analysis
  environment:
    - PYTHON_VERSION=3
  only:
    - web
    - trigger
    - merge requests
  tags:
    - pp-new-develop

tests-service:
  stage: tests
  environment:
    - PYTHON_VERSION=3
  only:
    - web
    - trigger
    - merge requests
  tags:
    - pp-new-develop

flake8:
  extends: static-analysis-service
  script:
    - nox -s flake8

isort:
  extends: static-analysis-service
  script:
    - nox -s isort -- check

yapf:
  extends: static-analysis-service
  script:
    - nox -s yapf -- check


mainnet:
  extends: tests-service
  script:
    - nox -s mainnet-tests

testnet:
  extends: tests-service
  script:
    - nox -s testnet-tests
