image: 'python:3.7'

stages:
  - static analysis
  - tests
  - package

.analyzers:
  stage: static analysis
  before_script:
    - pip3 install -r requirements_dev.txt --no-cache-dir
  only:
    - web
    - trigger
    - merge requests
  tags:
    - pp-new-develop

.tests:
  stage: tests
  variables:
    PYTHON_VERSION: 3
  only:
    - web
    - trigger
    - merge requests
  tags:
    - pp-new-develop

flake8:
  extends: .analyzers
  script:
    - nox -s flake8

isort:
  extends: .analyzers
  script:
    - nox -s isort -- check

yapf:
  extends: .analyzers
  script:
    - nox -s yapf -- check

mainnet:
  extends: .tests
  script:
    - nox -s mainnet-tests
  artifacts:
    paths:
      - reports
    expire_in: 10 mins
    when: always

testnet:
  extends: .tests
  script:
    - nox -s testnet-tests
  artifacts:
    paths:
      - reports
    expire_in: 10 mins
    when: always

pack-zip:
  stage: package
  script: zip reports.zip reports
  artifacts:
    paths:
      - reports.zip
    expire_in: 3 hours
  when: always
  only:
    - web
    - trigger
    - merge requests
  tags:
    - pp-new-develop
