image: 'python:3.7'

stages:
  - static analysis
  - tests

.analyzers:
  stage: static analysis
  only:
    - web
    - trigger
    - merge requests
  tags:
    - pp-new-develop

.analyzers-with-requirements:
  extends: .analyzers
  before_script:
    - pip3 install -r requirements_dev.txt --no-cache-dir

.tests:
  stage: tests
  variables:
    PYTHON_VERSION: 3
  artifacts:
    paths:
      - reports
    expire_in: 3 hours
    when: always
  only:
    - web
    - trigger
    - merge requests
  tags:
    - pp-new-develop

flake8:
  extends: .analyzers-with-requirements
  script:
    - nox -s flake8

isort:
  extends: .analyzers-with-requirements
  script:
    - nox -s isort -- check

yapf:
  extends: .analyzers-with-requirements
  script:
    - nox -s yapf -- check

mypy:
  extends: .analyzers
  variables:
    PYTHON_VERSION: 3
  script:
    - nox -s mypy

mainnet:
  extends: .tests
  script:
    - nox -s mainnet-tests
  
testnet:
  extends: .tests
  script:
    - nox -s testnet-tests
